#!/bin/bash
# Script to install dotfiles to the current user's homefolder

# .profile
echo "* Deploying .profile"
cp -f .profile $HOME/

# ZSH
if [[ $(command -v zsh) ]]; then
	echo "* Deploying zshrc.conf"
	echo "source '$(pwd)/zsh/zshrc_manager.sh'" > $HOME/.zshrc
else
	echo "- zsh is not installed. Skipping."
fi


# Vim
if [[ $(command -v vim) ]]; then
	echo "* Deploying .vimrc"
	echo "so $HOME/dot/vim/vimrc.vim" > $HOME/.vimrc
	rm -rf $HOME/.vim
	ln -sf $(pwd)/vim $HOME/.vim
else
	echo "- vim is not installed. Skipping."
fi


# Lxterminal
if [[ $(command -v lxterminal) ]]; then
	echo "* Deploying lxterminal.conf"
	ln -sf $(pwd)/lxterminal/lxterminal.conf $HOME/.config/lxterminal/lxterminal.conf
else
	echo "- lxterminal is not installed. Skipping."
fi


# I3wm
if [[ $(command -v i3) ]]; then
	echo "* Deploying i3wm config"
	ln -sf $(pwd)/i3/config $HOME/.config/i3/config
else
	echo "- i3wm is not installed. Skipping."
fi
