#!/bin/bash
# Script to install dotfiles to the current user's homefolder

# ZSH
if [[ $(command -v /usr/bin/zsh) ]]; then
	echo "* Deploying zshrc.conf"
	echo "source '$(pwd)/zsh/zshrc_manager.sh'" > $HOME/.zshrc
else
	echo "- zsh not installed. Skipping."
fi


# Lxterminal
if [[ $(command -v /usr/bin/lxterminal) ]]; then
	echo "* Deploying lxterminal.conf"
	ln -sf $(pwd)/lxterminal/lxterminal.conf $HOME/.config/lxterminal/lxterminal.conf
else
	echo "- lxterminal not installed. Skipping."
fi
