#!/bin/bash
# i3 startup script profiles

profile=$(uname -n)


desktop() {
	nvidia-settings -l
	transmission-daemon
}


x250() {
	echo
}


case $profile in
	desktop) "desktop" ;;
	x250) "x250" ;;
esac
