#!/bin/bash
# i3 startup script profiles

profile=$(uname -n)


eivind-desktop() {
	nvidia-settings -l
}


eivind-x250() {
	echo
}


case $profile in
	eivind-desktop) "eivind-desktop" ;;
	eivind-x250) "eivind-x250" ;;
esac
