#!/bin/bash
# i3 startup script profiles

profile=$(uname -n)

desktop() {
	nvidia-settings -l
	if (( ! $(pgrep transmission-daemon) )); then
		transmission-daemon
	fi
}

desktop-mini() {
	sh ~/.screenlayout/3x-dell.sh
}

x250() {
	echo
}

case $profile in
	desktop) "desktop" ;;
	desktop-mini) "desktop-mini" ;;
	x250) "x250" ;;
esac
