#!/bin/bash
# i3blocks show highest cpu usage process

yellowPercentage=80

highestprocstring="$(ps -eo comm,%cpu,%mem --sort=-%cpu --no-headers | head -n1 | tr -s ' ')"

echo "$highestprocstring"
echo "$highestprocstring"
