#!/bin/bash
# Check temperature

mediumWarning=60
highWarning=75

temperature=$(sensors -u | grep -m 1 -A 1 "Physical id 0:" | tail -n 1 | tr -s ' ' | cut -d ' ' -f3 | cut -d '.' -f1)

echo "$temperature C"
echo "$temperature C"

# check colors
if (( $temperature >= $highWarning )); then
	echo "#FF0000"
elif (( $temperature >= $mediumWarning )); then
	echo "#FFFF00"
else
	echo "#00FFFF"
fi
